spring.application.name=wallet-optimizer
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
frontend.url=${FRONTEND_URL}

spring.jpa.hibernate.ddl-auto=update

